name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # You can use 'adopt', 'zulu', etc.
        java-version: '11'

    - name: Compile Java code
      run: javac -d out src/com/ontrack/model/*.java src/com/ontrack/service/*.java

    - name: Run Tests
      run: |
        javac -cp .:out:lib/junit-platform-console-standalone-1.7.1.jar -d test-classes test/com/ontrack/service/TaskInboxServiceTest.java
        java -jar lib/junit-platform-console-standalone-1.7.1.jar --class-path out:test-classes --scan-class-path

